CREATE TABLE job_history
   ( employee_id INT
   , start_date VARCHAR(12)
   , end_date VARCHAR(12)
   , job_id VARCHAR(10)
   , department_id INT
   ) ;
   
   
INSERT INTO job_history
      VALUES (102
   , '13-JAN-1993'
   , '24-JUL-1998'
   , 'IT_PROG'
   , 60);
INSERT INTO job_history
         VALUES (101
   , '21-SEP-1989'
   , '27-OCT-1993'
   , 'AC_ACCOUNT'
   , 110);
INSERT INTO job_history
         VALUES (101
   , '28-OCT-1993'
   , '15-MAR-1997'
   , 'AC_MGR'
   , 110);
INSERT INTO job_history
         VALUES (201
   , '17-FEB-1996'
   , '19-DEC-1999'
   , 'MK_REP'
   , 20);
INSERT INTO job_history
         VALUES (114
   , '24-MAR-1998'
   , '31-DEC-1999'
   , 'ST_CLERK'
   , 50
   );
INSERT INTO job_history
         VALUES (122
   , '01-JAN-1999'
   , '31-DEC-1999'
   , 'ST_CLERK'
   , 50
   );
INSERT INTO job_history
         VALUES (200
   , '17-SEP-1987'
   , '17-JUN-1993'
   , 'AD_ASST'
   , 90
   );
INSERT INTO job_history
         VALUES (176
   , '24-MAR-1998'
   , '31-DEC-1998'
   , 'SA_REP'
   , 80
   );
INSERT INTO job_history
         VALUES (176
   , '01-JAN-1999'
   , '31-DEC-1999'
   , 'SA_MAN'
   , 80
   );
INSERT INTO job_history
         VALUES (200
   , '01-JUL-1994'
   , '31-DEC-1998'
   , 'AC_ACCOUNT'
   , 90
   );